sudo: required
services:
    - docker

before_install:
    - docker build -t kingian95/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true kingian95/react-test npm run test

after_success:
    - docker build -t kingian95/multi-client ./client
    - docker build -t kingian95/multi-nginx ./nginx
    - docker build -t kingian95/multi-client ./client
    - docker build -t kingian95/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push kingian95/multi-client
    - docker push kingian95/multi-nginx 
    - docker push kingian95/multi-client
    - docker push kingian95/multi-worker